
title: Autumn Rose Management Company, LLC
description: Autumn Rose Management Company (ARMC) is currently a pre-launch sports betting entity. We aim to eventually
provide institutional and high-net worth investors an avenue to material returns that are independent from broader
financial markets through quantitative sports betting.
show_downloads: false
theme: jekyll-theme-tactile